import { AppConfigSchema, type AppConfig } from '../src/config/schema.js';

export const validEnv = {
  NODE_ENV: 'test',
  BTS_LOG_LEVEL: 'debug',
  BTS_DRY_RUN: 'true',
  SENTRY_AUTH_TOKEN: 'sentry-secret',
  SENTRY_ORG_SLUG: 'acme',
  SENTRY_PROJECT_SLUG: 'web',
  SENTRY_ENVIRONMENT: 'production',
  SENTRY_REGION_URL: 'https://sentry.io',
  SENTRY_WEBHOOK_SECRET: 'sentry-webhook',
  GITHUB_APP_ID: '123',
  GITHUB_APP_PRIVATE_KEY: 'github-private-key',
  GITHUB_INSTALLATION_ID: '456',
  GITHUB_OWNER: 'acme',
  GITHUB_REPO: 'back-to-service',
  GITHUB_TARGET_INSTALLATION_ID: '789',
  GITHUB_TARGET_OWNER: 'acme',
  GITHUB_TARGET_REPO: 'web',
  GITHUB_WEBHOOK_SECRET: 'github-webhook',
  GITHUB_BASE_BRANCH: 'main',
  VERCEL_TOKEN: 'vercel-secret',
  VERCEL_TEAM_ID: 'team_123',
  VERCEL_TEAM_SLUG: 'acme-team',
  VERCEL_PROJECT_ID: 'prj_123',
  VERCEL_PROJECT_NAME: 'web',
  AUTOPILOT_ENABLED: 'true',
  AUTOPILOT_DRY_RUN: 'false',
  AUTOPILOT_CONFIDENCE_THRESHOLD: '0.9',
  AUTOPILOT_MAX_FILES_CHANGED: '6',
  AUTOPILOT_MAX_LINES_CHANGED: '300',
  AUTOPILOT_ALLOWED_ACTIONS: 'create_issue,update_issue,trigger_agent,trigger_claude,open_pr,merge_pr,rollback,run_recovery_hook',
  AUTOPILOT_PROTECTED_PATHS: '.github/workflows/**,infra/**',
  AUTOPILOT_ALLOW_MERGE: 'true',
  AUTOPILOT_ALLOW_DEPLOY: 'true',
  AUTOPILOT_ALLOW_ROLLBACK: 'true',
  AUTOPILOT_ALLOW_RECOVERY_HOOK: 'true',
  AUTOPILOT_EMERGENCY_STOP: 'false',
  BTS_TARGET_PRODUCTION_URL: '',
  BTS_TARGET_HEALTH_CHECK_PATH: '/',
  BTS_TARGET_HEALTH_CHECK_STATUS: '200',
  BTS_TARGET_HEALTH_CHECK_TIMEOUT_MS: '10000',
  BTS_TARGET_VERCEL_PROJECT_ID: '',
  BTS_TARGET_VERCEL_TEAM_ID: '',
  BTS_TARGET_SENTRY_PROJECT_SLUG: '',
  PERF_ENABLED: 'true',
  PERF_MIN_SAMPLE_COUNT: '20',
  PERF_P95_THRESHOLD_MS: '1000',
  PERF_REGRESSION_RATIO: '1.5',
  PERF_ALLOWED_OPS: 'http.server,db,http.client,navigation',
  POSTHOG_ENABLED: 'false',
  POSTHOG_PERSONAL_API_KEY: 'posthog-secret',
  POSTHOG_PROJECT_ID: '12345',
  POSTHOG_HOST: 'https://us.posthog.com',
  POSTHOG_IMPACT_EVENTS: 'signup_completed,checkout_completed,purchase_completed',
  POSTHOG_IMPACT_WINDOW_HOURS: '24',
  POSTHOG_IMPACT_BASELINE_HOURS: '24',
  BTS_REPAIR_PROVIDER: 'claude',
} satisfies NodeJS.ProcessEnv;

export const validPolicy: AppConfig['autopilot'] = {
  enabled: true,
  dryRun: false,
  emergencyStop: false,
  confidenceThreshold: 0.85,
  maxFilesChanged: 5,
  maxLinesChanged: 250,
  allowedActions: ['create_issue', 'update_issue', 'trigger_agent', 'trigger_claude', 'open_pr', 'merge_pr', 'redeploy', 'rollback', 'run_recovery_hook'],
  protectedPaths: ['.github/workflows/**', 'infra/**', 'prisma/schema.prisma'],
  allowMerge: true,
  allowDeploy: true,
  allowRollback: true,
  allowRecoveryHook: true,
};

export function createTestConfig(overrides: Record<string, unknown> = {}): AppConfig {
  const base = {
    runtime: { nodeEnv: 'test', logLevel: 'debug', dryRun: true },
    sentry: {
      authToken: 'sentry-secret',
      orgSlug: 'acme',
      projectSlug: 'web',
      environment: 'production',
      regionUrl: 'https://sentry.io',
    },
    github: {
      appId: '123',
      privateKey: 'github-private-key',
      installationId: '456',
      owner: 'acme',
      repo: 'back-to-service',
      baseBranch: 'main',
      targetOwner: 'acme',
      targetRepo: 'web',
    },
    vercel: {
      token: 'vercel-secret',
      teamId: 'team_123',
      projectId: 'prj_123',
    },
    target: {
      healthCheckPath: '/',
      healthCheckExpectedStatus: 200,
      healthCheckTimeoutMs: 10_000,
      ...((overrides.target as Record<string, unknown>) ?? {}),
    },
    recovery: {
      maxAttempts: 3,
      partialToleranceCycles: 2,
      minDeployAgeSeconds: 60,
      needsHumanLabel: 'needs-human',
      resolvedLabel: 'auto-recovery-resolved',
      ...((overrides.recovery as Record<string, unknown>) ?? {}),
    },
    performance: {
      enabled: true,
      minSampleCount: 20,
      p95ThresholdMs: 1_000,
      regressionRatio: 1.5,
      allowedOps: ['http.server', 'db', 'http.client', 'navigation'],
      ...((overrides.performance as Record<string, unknown>) ?? {}),
    },
    posthog: {
      enabled: false,
      personalApiKey: 'posthog-secret',
      projectId: '12345',
      host: 'https://us.posthog.com',
      impactEvents: ['signup_completed', 'checkout_completed', 'purchase_completed'],
      windowHours: 24,
      baselineHours: 24,
      ...((overrides.posthog as Record<string, unknown>) ?? {}),
    },
    repair: {
      provider: 'claude',
      ...((overrides.repair as Record<string, unknown>) ?? {}),
    },
    autopilot: validPolicy,
  };

  const { target: _t, recovery: _r, performance: _p, posthog: _ph, repair: _repair, ...rest } = overrides;
  return AppConfigSchema.parse({ ...base, ...rest });
}
