import type { AppConfig } from '../src/config/schema.js';

export const validEnv = {
  NODE_ENV: 'test',
  BTS_LOG_LEVEL: 'debug',
  BTS_DRY_RUN: 'true',
  SENTRY_AUTH_TOKEN: 'sentry-secret',
  SENTRY_ORG_SLUG: 'acme',
  SENTRY_PROJECT_SLUG: 'web',
  SENTRY_ENVIRONMENT: 'production',
  SENTRY_REGION_URL: 'https://sentry.io',
  SENTRY_WEBHOOK_SECRET: 'sentry-webhook',
  GITHUB_APP_ID: '123',
  GITHUB_APP_PRIVATE_KEY: 'github-private-key',
  GITHUB_INSTALLATION_ID: '456',
  GITHUB_OWNER: 'acme',
  GITHUB_REPO: 'web',
  GITHUB_WEBHOOK_SECRET: 'github-webhook',
  GITHUB_BASE_BRANCH: 'main',
  VERCEL_TOKEN: 'vercel-secret',
  VERCEL_TEAM_ID: 'team_123',
  VERCEL_TEAM_SLUG: 'acme-team',
  VERCEL_PROJECT_ID: 'prj_123',
  VERCEL_PROJECT_NAME: 'web',
  AUTOPILOT_ENABLED: 'true',
  AUTOPILOT_DRY_RUN: 'false',
  AUTOPILOT_CONFIDENCE_THRESHOLD: '0.9',
  AUTOPILOT_MAX_FILES_CHANGED: '6',
  AUTOPILOT_MAX_LINES_CHANGED: '300',
  AUTOPILOT_ALLOWED_ACTIONS: 'create_issue,update_issue,open_pr,merge_pr,rollback,run_recovery_hook',
  AUTOPILOT_PROTECTED_PATHS: '.github/workflows/**,infra/**',
  AUTOPILOT_ALLOW_MERGE: 'true',
  AUTOPILOT_ALLOW_DEPLOY: 'true',
  AUTOPILOT_ALLOW_ROLLBACK: 'true',
  AUTOPILOT_ALLOW_RECOVERY_HOOK: 'true',
  AUTOPILOT_EMERGENCY_STOP: 'false',
} satisfies NodeJS.ProcessEnv;

export const validPolicy: AppConfig['autopilot'] = {
  enabled: true,
  dryRun: false,
  emergencyStop: false,
  confidenceThreshold: 0.85,
  maxFilesChanged: 5,
  maxLinesChanged: 250,
  allowedActions: ['create_issue', 'update_issue', 'open_pr', 'merge_pr', 'redeploy', 'rollback', 'run_recovery_hook'],
  protectedPaths: ['.github/workflows/**', 'infra/**', 'prisma/schema.prisma'],
  allowMerge: true,
  allowDeploy: true,
  allowRollback: true,
  allowRecoveryHook: true,
};
